import { expect, test } from './helpers/test'

test('undo restores the template and page size the builder shows', async ({ page }) => {
  await page.goto('/app')
  await page.getByRole('button', { name: 'Quick invoice' }).click()
  await page.getByRole('tab', { name: 'Properties' }).click()
  const gallery = page.getByRole('radiogroup', { name: 'Template gallery' })
  const initial = await gallery.getByRole('radio', { checked: true }).textContent()

  await gallery.getByRole('radio', { name: 'Swiss' }).click()
  await expect(gallery.getByRole('radio', { name: 'Swiss' })).toHaveAttribute('aria-checked', 'true')
  await page.getByRole('button', { name: 'Undo' }).click()
  await expect(gallery.getByRole('radio', { checked: true })).toHaveText(initial ?? '')

  const headerSize = page.getByRole('combobox', { name: 'Page size' }).first()
  const initialSize = await headerSize.textContent()
  await headerSize.click()
  await page.getByRole('option', { name: 'A5' }).click()
  await expect(headerSize).toHaveText(/^a5/i)
  await page.getByRole('button', { name: 'Undo' }).click()
  await expect(headerSize).toHaveText(initialSize ?? '')
})

test('header and footer presets show only for templates without their own header', async ({ page }) => {
  await page.goto('/app')
  await page.getByRole('button', { name: 'Quick invoice' }).click()
  await page.getByRole('tab', { name: 'Properties' }).click()
  const gallery = page.getByRole('radiogroup', { name: 'Template gallery' })
  await gallery.getByRole('radio', { name: 'Minimal' }).click()
  await expect(page.getByText('Header style')).toBeVisible()
  await gallery.getByRole('radio', { name: 'Noir Ledger' }).click()
  await expect(page.getByText('Header style')).toHaveCount(0)
  await expect(page.getByText('Accent color')).toBeVisible()
})

test('the selected item shows its price in the project currency', async ({ page }) => {
  await page.goto('/services')
  const form = page.getByRole('region', { name: 'New service' })
  await form.getByLabel('Service name').fill('Logo design')
  await form.getByLabel('Price').fill('1200')
  await form.getByRole('button', { name: 'Save' }).click()
  await expect(page.getByRole('listitem', { name: 'Logo design' })).toBeVisible()

  await page.goto('/app')
  await page.getByRole('button', { name: 'Quick invoice' }).click()
  await expect(page).toHaveURL(/\/(documents|projects)\//)
  await page.goto('/app')
  await page.getByRole('link', { name: 'Untitled project' }).click()
  await page.getByLabel('Currency', { exact: true }).selectOption('JPY')
  await page.getByLabel('Number and date format').fill('en-US')
  await page.getByRole('button', { name: 'Save project' }).click()
  await expect(page.getByLabel('Currency', { exact: true })).toHaveValue('JPY')

  await page.getByRole('listitem', { name: 'Invoice' }).getByRole('link').first().click()
  await page.getByLabel('Add from services').selectOption({ label: 'Logo design' })
  await page.locator('aside').getByText('Logo design').first().click()
  await expect(page.getByLabel('Unit price', { exact: true })).toHaveValue('120000')
})

test('Noir Ledger can switch to a light background for printing', async ({ page }) => {
  await page.goto('/app')
  await page.getByRole('button', { name: 'Quick invoice' }).click()
  await page.getByRole('tab', { name: 'Properties' }).click()
  const gallery = page.getByRole('radiogroup', { name: 'Template gallery' })
  const background = () => page.locator('#document-root').evaluate((el) => getComputedStyle(el).backgroundColor)
  await expect(page.getByLabel('Light background (saves ink)')).toHaveCount(0)
  await gallery.getByRole('radio', { name: 'Noir Ledger' }).click()
  await expect.poll(background).toBe('rgb(21, 21, 21)')
  await page.getByLabel('Light background (saves ink)').check()
  await expect.poll(background).toBe('rgb(255, 255, 255)')
})
