// Every label printed on documents, kept in one place so a translation can replace it later.
export const DOC_LABELS = {
  billTo: 'Bill to',
  item: 'Item',
  description: 'Description',
  quantity: 'Qty',
  unitPrice: 'Unit price',
  amount: 'Amount',
  subtotal: 'Subtotal',
  tax: 'Tax',
  taxIncluded: 'Includes tax',
  grandTotal: 'Grand total',
  issued: 'Issued',
  dueDate: 'Due',
  validUntil: 'Valid until',
  number: 'Number',
  numberShort: 'No.',
  from: 'From',
  contact: 'Contact',
  reference: 'Reference',
  page: 'Page',
  thankYou: 'Thank you.',
  questions: 'Questions?',
  withThanks: 'With thanks,',
  paymentSchedule: 'Payment schedule',
  clientSignature: 'Client signature',
  nameAndDate: 'Name and date',
  footerPayment: 'Please transfer within 14 days to the bank account stated on the invoice.',
  footerThanks: 'Thank you for your business.',
  legalNotice: 'These clauses are a plain-language starting point, not legal advice. Review them for your country before sending.',
} as const
