// Copy for the welcome screen and the home command center.
export const HOME_COPY = {
  welcomeTitleStart: 'Every client job,',
  welcomeTitleAccent: 'on paper',
  welcomeTitleEnd: ', from quote to thank-you.',
  welcomeLead: 'Ten documents, one project. Free, offline, and kept on this device.',
  setupTitle: 'Your business',
  setupLead: 'The sender on every quote, invoice and agreement.',
  setupSubmit: 'Start',
  setupHint: 'Adds a sample project to explore',
  skip: 'Skip for now',
  search: 'Search projects or name a new one',
  newProject: 'New project',
  newProjectNamed: (title: string) => `New project "${title}"`,
  newProjectHint: 'One client job, from quote to feedback',
  quickInvoice: 'Quick invoice',
  quickInvoiceHint: 'Bill a client without a full project',
  needsYou: 'Needs you',
  start: 'Start',
  projects: 'Projects',
  workspace: 'Workspace',
  noMatches: 'No projects match.',
  noProjects: 'No projects yet. Name one above to start.',
} as const
